name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.18.3 # specify the version of Deno you want to use

      - name: Update PATH
        run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Run tests
        run: deno test --allow-all

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          subcommand: "push"
          project: "reduxintroduction"
          entrypoint: "file:///src/main.jsx" # TODO: update entrypoint
